version: '3.7'
services:
 s3fs:
  container_name: s3fs
  image: jkaninda/s3fs
  privileged: true
  restart: always
  tty: true
  devices:
    - "/dev/fuse"
  volumes:
    - ./data:/s3mnt
  environment:
   - ACCESS_KEY=${ACCESS_KEY}
   - SECRET_KEY=${SECRET_KEY}
   - BUCKETNAME=${BUCKETNAME}
   - S3_URL=${S3_URL}